pr:
  - master

resources:
  - repo: self

variables:
  vmImageName: 'windows-2019'
  GitVersion.SemVer: ''

stages:          
  - stage: StaticAnalysis
    jobs:
    - job: StaticAnalysis
      pool:
        vmImage: $(vmImageName)

      steps:
      - task: PowerShell@2
        inputs:
          filePath: ./build.ps1 
          arguments: -Task StaticAnalysis
          
  - stage: Build
    jobs:
    - job: Build
      pool:
        vmImage: $(vmImageName)
      
      steps:
      - task: PowerShell@2
        inputs:
          filePath: ./build.ps1
          arguments: -Task Build

  - stage: Test
    jobs:
    - job: Test
      strategy:
        maxParallel: 3
        matrix:
          Linux:
            vmImage: 'ubuntu-16.04'
          MacOS:
            vmImage: 'macOS-10.14'
          Windows:
            vmImage: 'windows-2019'
      pool:
        vmImage: $(vmImage)

      steps:
      - task: PowerShell@2
        inputs:
          filePath: ./build.ps1
          arguments: -Task Tests

  - stage: Publish
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
    - job: Publish
      pool:
        vmImage: $(vmImageName)
      
      steps:
      - task: PowerShell@2
        inputs:
          filePath: ./build.ps1
          arguments: -Task Publish
        env:
          KubePromptApiKey: $(KubePromptApiKey)
